#!/bin/sh

# This is incomplete...

# Follow this guide
# https://gist.github.com/tatumroaquin/c6464e1ccaef40fd098a4f31db61ab22

sudo pacman -S --needed --noconfirm qemu-full qemu-img libvirt virt-install virt-manager virt-viewer edk2-ovmf dnsmasq swtpm guestfs-tools libosinfo tuned
sudo systemctl enable libvirtd.service

# verify
sudo virt-host-validate qemu





# Another guide
# https://nmanzi.com/posts/windows-guest-on-linux-mint/
# On the final screen select “Customize the configuration…”:
#
#    Set the chipset to Q35
#    Set the firmware to UEFI x86_64:/usr/share/OVMF/OVMF_CODE_4M.ms.fd
#    Change the NIC to use NAT and the virtio device model
#    Set the SATA Disk 1 bus to VirtIO and cache mode to “writeback” for best performance
#    Add the Virtio Drivers ISO as a CDROM device
#    (If using TPM) Add a TPM device (emulated or passthrough) with version 2.0

# Click “Begin installation” to end this quest.


