#!/usr/bin/env bash

sudo pacman -S --needed --noconfirm pipewire
sudo pacman -S --needed --noconfirm pipewire-pulse
sudo pacman -S --needed --noconfirm pipewire-alsa
sudo pacman -S --needed --noconfirm pipewire-jack
sudo pacman -S --needed --noconfirm wireplumber
#sudo pacman -S --needed --noconfirm pavucontrol
sudo pacman -S --needed --noconfirm pulsemixer


# Enable services
systemctl --user enable --now pipewire.service
systemctl --user enable --now pipewire-pulse.service
systemctl --user enable --now wireplumber.service