#!/usr/bin/env bash

# Create symlinks to dotfiles

ln -sfn "$(pwd)/../dotfiles/picom" ~/.config/picom
ln -sfn "$(pwd)/../dotfiles/i3" ~/.config/i3
ln -sfn "$(pwd)/../dotfiles/i3blocks" ~/.config/i3blocks
ln -sfn "$(pwd)/../dotfiles/rofi" ~/.config/rofi
ln -sfn "$(pwd)/../dotfiles/xfce4" ~/.config/xfce4
ln -sfn "$(pwd)/../dotfiles/.bashrc" ~/.bashrc
ln -sfn "$(pwd)/../dotfiles/.xinitrc" ~/.xinitrc


# Create symlink to wallpapers

mkdir -p ~/Pictures
ln -sfn "$(pwd)/../Wallpapers" ~/Pictures/Wallpapers