#!/usr/bin/env bash

# Create symlinks to dotfiles

ln -sfn ~/archi3/dotfiles/picom ~/.config/picom
ln -sfn ~/archi3/dotfiles/i3 ~/.config/i3
ln -sfn ~/archi3/dotfiles/i3blocks ~/.config/i3blocks
ln -sfn ~/archi3/dotfiles/rofi ~/.config/rofi
ln -sfn ~/archi3/dotfiles/xfce4 ~/.config/xfce4
ln -sfn ~/archi3/dotfiles/polybar ~/.config/polybar
ln -sfn ~/archi3/dotfiles/alacritty ~/.config/alacritty
ln -sfn ~/archi3/dotfiles/.bashrc ~/.bashrc
ln -sfn ~/archi3/dotfiles/.xinitrc ~/.xinitrc


# Create symlink to wallpapers

mkdir -p ~/Pictures
ln -sfn "~/archi3/Wallpapers ~/Pictures/Wallpapers